### PR TITLE
File not used in project

### PR DESCRIPTION
**Pull request by jcommelin**
The following four files are also not used.
But they might contain useful info.

```
for_mathlib.finsupp_prod_inv
for_mathlib.uniform_space.pi
for_mathlib.sheaves.presheaf_of_rings_maps
for_mathlib.sheaves_of_types
```

### CODE REVIEW

**Comment by jcommelin** [comment]
@PatrickMassot @kbuzzard Please have a look at what we should do with the other four files mentioned above.

**Comment by kbuzzard** [comment]
Aah! sheaves_of_types was me just playing around, before Ramon finished his project enabling me to steal it. Yes, definitely delete that!

**Comment by PatrickMassot** [comment]
https://github.com/leanprover-community/mathlib/blob/master/src/topology/uniform_space/pi.lean

**Comment by jcommelin** [comment]
I've now removed all files in the list.

**Pull request merged**
